<a href="https://colab.research.google.com/github/EduardoWS/python-for-ML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Comandos Básicos do Numpy

In [3]:
import numpy as np

a = np.array([1, 2, 3])    #array é uma lista com elementos do mesmo tipo

In [4]:
print(a)

[1 2 3]


In [5]:
#array com mais de uma dimensão (matriz):
b = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

In [6]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
c = np.zeros((4, 3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
d = np.ones((4, 3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
b.max()

9

In [15]:
b.min()

1

In [16]:
b.sum()   #soma todos os elementos da matriz

45

In [17]:
b.mean()    #média de todos os elementos da matriz

5.0

In [18]:
b.std()   #desvio padrão de todos os elementos da matriz

2.581988897471611